version: "3"

services:
  api:
    build: .
    container_name: api
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
    environment:
      MONGO_URL: mongodb://mongo:27017/db
    depends_on:
      # - cassandra
      - mongo

  # cassandra:
  #   container_name: cassandra
  #   image: cassandra:4.0
  #   volumes:
  #     - ./cassandra:/var/lib/cassandra

  mongo:
    container_name: mongo
    image: mongo:4.4
    ports:
      - 27017:27017
    volumes:
      - "./volumes/mongo/:/data/db"
