version: "3"

services:
  api:
    build: .
    container_name: api
    ports:
      - 8000:8000
    volumes:
      - ./src:/app/src
    environment:
      MONGO_URL: mongodb://mongo:27017/db
    depends_on:
      - cassandra
      - mongo

  cassandra:
    container_name: cassandra
    image: bitnami/cassandra:latest
    ports:
      - 9042:9042
    environment: 
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=cassandra
    volumes:
      - ./volumes/cassandra:/bitnami
      - ./cassandra-init-scripts:/docker-entrypoint-initdb.d

  mongo:
    container_name: mongo
    image: mongo:4.4
    ports:
      - 27017:27017
    volumes:
      - "./volumes/mongo/:/data/db"
